import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@repo/common/cn";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Pixora-web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        `${geistSans.variable} ${geistMono.variable}`,
        "font-[var(--font-inter)]",
        "w-screen h-screen bg-gradient-to-b from-background-black from-0% via-background-black via-25% to-pixora-950 to-95%"
      )}>
        {children}
      </body>
    </html>
  );
}
